AFM-SPM/TopoStats

dnatracing.py
During the previous update, some lines were broken into two. I just realised that this would cause errors, so I fixed it by adding brackets.
=> Fix errors caused by line breaking

dnatracing.py, pygwytracing.py
The relative file path made it so certain files were not created - resolved by amending to fullpath.
Incorrect reference to self made it so all image names and image paths in the tracestats.json files were the same regardless of different files being used.
=> Relative File Path & Wrong Filename Bug Fixes

tests/test_thresholds.py, topostats/thresholds.py
resolves #118 
This adds a simple [factory design pattern](https://realpython.com/factory-method-python/) to perform the threshold calculation on images.
It includes tests which show how to use it (and validate) and it should be easy to add additional methods.
To use it in `dev-remove-gwyddion` it would be necessary to [cherry-pick](https://rse.shef.ac.uk/blog/2021-04-23-cherry-pick/) commit `8f0542b` to get it into the branch (or possibly a `rebase` but I'm unsure how divergent `dev` and `dev-remove-gwyddion` are and that may cause lots of problems).
It can then be used with...
```
from topostats.thresholds import threshold
image_threshold = threshold(<image>, method='otsu')
```
...where `<image>` is the `np.ndarray` representation of the image at whatever stage of the processing.
=> 118 | Adds a factory method to make thresholding flexible

topostats/io.py, topostats/run_topostats.py
Resolves #159 
Plots the `raw_height` of the Bruker image to `00-raw_height.png` resolving #159.
The reason I'd not included this previously is I was confused why the `pySPM.SPM` that the `extract_channel()` plots couldn't be plotted, its because this object has the attribute `pixels` which is what should be plotted.
That said I'm not entirely sure why this, which is the plot of `pySPM.SPM.pixels` differs from the plot of pixels as I can't see why/where the `self.images["pixels"]` is modified in comparison to the extraction and so the two should match. :shrug: 
I've also introduced a short function `topostats.io.write_yaml()` that writes the configuration used to YAML in the output directory which is an interim step to addressing #111 but not an absolute solution.
=> 159 | Introduces correct "raw_height" plot; adds write_yaml()

tests/test_grains_minicircle.py, topostats/grains.py
In investigating #183 I've discovered a problem related to thresholds and filtering when only a single grain is found.
The image `20220601_NDP52_FL_10ng_PLO_HEPES_20mM_NaCl_50mM.0_00021.spm` crashed with the error...
```bash
IndexError: cannot do a non-empty take from an empty axes.
```
This arises from the `Grains` class and is caused when the method `.calc_minimum_grain_size()` is called and only one grain has been detected. The code calculates the minimum grain size by first calculating the area of all grains...
```python
grain_areas = np.array([grain.area for grain in self.region_properties])
```
Then only a subset of grains were retained when the area exceeded a threshold...
```python
grain_areas = grain_areas[grain_areas > threshold(grain_areas, method=self.threshold_method)]
``` …
=> 183 | Handling single grains

Plotting.py
Allowing csv files as input for Plotting.py and fixing print statments so that they work with Python3.
The rest of Plotting.py still needs refactoring since it's based on the assumption that the stats from all the spm files are combined in one file, which isn't the case with new TopoStats.
=> Allowing csv files as input for Plotting.py

tests/test_utils.py, topostats/run_topostats.py, topostats/utils.py
This PR orders the output directories into a structure similar to how the files are found.
Here, using "./data/" as the `base_dir` in the config file, we have multiple directories containing multiple files, i.e:
The PR replaces the `base_dir` of the `image_path` with the `output_dir`, keeping the subsequent directory structure after.
This creates an output mirroring the inputs, i.e:
Further work will be done to remove the `minicircle<#>` directories but this should only happen after:
1) The output files are truncated.
2) The output files are re-named to reflect the file they originated from
In order to avoid overwriting output files.
=> Maxgamill sheffield/224 output file dir structure

tests/test_filters.py, tests/test_grainstats.py, topostats/filters.py
.spm data seems like it is encoded as a value and a unit. This change adds a dictionary to the `extract_pixel_to_nm_scaling` function in the `Filters` class and uses the units to rescale produced value of `self.pixel_to_nm_scaling`.
Tests have also been added via `parameterize` so there is room for non-square tests too.
Currently, this is only a quick fix but has a framework in place to address some other issues I've found associated with this:
- It is currently all in reference to "nm" where it may be best to have SI units which can then propagate to the grainstats and dnatracing stats.
- Framework is present within the function to obtain px-to-nm values for non-square images but further changes would be needed to propagate these values through to later functions as the output would …
=> pixel to nm scaling no longer assumes xy in nm

topostats/filters.py
Fixes the issue pointed out in #280 where the all set images are the same for pixels onwards. Fixed by making copies of arrays and not modifying the same array.
=> tilt and rows return copies + general doc cleanup

topostats/plottingfuncs.py
Single line change and no test changes - change makes it so that pathlib notation can always be used within `Images`
Closes #278
=> Changed to Path(output_dir)

tests/test_plottingfuncs.py, topostats/plotting_dictionary.yaml, topostats/plottingfuncs.py
This fixes an issues where image overwriting can occur due to the filenames containing an extension i.e:
`abc.0_001.spm` is passed into the filename argument as `abc.0_001`.
So in `plottingfuncs.py`, the `<path>.with_suffix(<ext>)` replaces the `.0_001` with `<ext>`.
This replaces the image if an image for `abc.0_000.spm` already exists.
The fix is to ensure no file extensions are input into filename, hence the removal from `plotting_dictionary.yaml` and in the tests.
=> Maxgamill sheffield/hotfix overwriting plots

topostats/default_config.yaml
resolves #296 
This PR simply fixes the issue documented in #296 where `run_topostats` would fail if not given a config file. The problem was merely that in a previous commit, the `default_config.yaml` was not updated alongside `example.yaml`.
=> Fix run_topostats crash

config/example.yaml, setup.cfg, tests/resources/process_scan_config.yaml, tests/resources/sample_config.yaml, topostats/default_config.yaml, topostats/run_topostats.py, topostats/validation.py
Resolves #299
Introduces the `topostats.validation` module with a single function `validate_config()` which uses [schema package](https://github.com/keleshev/schema) to validate the YAML configuration input.
This isn't something I've ever done before so I followed the examples [here](https://www.andrewvillazon.com/validate-yaml-python-schema/).
I've no idea what valid values/ranges should be for many of the fields and so have left crude validation of the type in place and created #302 to serve as a place for recording discussion of what valid ranges should be before updating.
For now I haven't introduced tests for `topostats/validation.py` as its seems somewhat circular to test schema validation and whilst it is perfectly feasible to test whether certain exceptions are raised I'm unsure …
=> Validate input configuration

config/example.yaml, tests/resources/process_scan_config.yaml, tests/resources/sample_config.yaml, topostats/default_config.yaml, topostats/grains.py, topostats/validation.py
This work removes `background` from the config files. 
I have not updated the example.yaml file as this is in the process of being removed.
This is because it is unnecessary because its used in the [skimage.morphology.labels](https://scikit-image.org/docs/stable/api/skimage.morphology.html#skimage.morphology.label) function where the input image to this is either the `mask` (in which the background is 0 by design) or a labelled image from `area_threshold` (which has a 0 background) or `remove_small_objects` (which also has 0 background by default)
=> Maxgamill sheffield/#288 remove background

setup.cfg
Currently `libasd` is _not_ imported in `topostats/io.py` as work is on-going to support reading such files.
For now, so that `dev` branch will install on non-x86_64 architectures this dependency has been removed. See #304 for possible solutions.
=> Remove libasd from setup.cfg

tests/conftest.py, tests/test_filters_minicircle.py, tests/test_grains_minicircle.py, tests/test_grainstats_minicircle.py, tests/test_plottingfuncs.py, topostats/default_config.yaml, topostats/filters.py, topostats/grains.py, topostats/plotting_dictionary.yaml, topostats/plottingfuncs.py, topostats/run_topostats.py, topostats/validation.py
* Rename `Image()` class option `type` to `image_type` as `type` is a core Python function.
* Rename `Image()` class option `pixel_to_nm_scaling_factor` to `pixel_to_nm_scaling` to be consistent across classes.
* Remove `channel` as an option to `Filter()` class.
* Remove `background` from `validate_config()`
* Remove `output_dir` from `Grains()` as it was only being used to make a directory and that is now done in `run_topostats.main()` / `process_scan()`.
* Tidied up docstring for `Grains()` class removing no longer used option `background`.
This also involved modifications to the validation schema and various tests.
(Noticed these as I was spending a little time updating the Notebook to work with the current codebase and started making the changes without creating an issue first).
=> Housekeeping and tidying up

.pre-commit-config.yaml, docs/contributing.md, setup.cfg
This introduces [pre-commit](https://rse.shef.ac.uk/blog/pre-commit/) with `black` and `flake8` linting to check the code as well as some checks on trailing whitespaces which will be corrected automatically.
Longer term I would like to incorporate the [pre-commit GitHub Action](https://github.com/marketplace/actions/pre-commit) so that PRs will not be accepted if the code does not pass the checks.
Further incorporating `pylint` into the `pre-commit` checks would be very sensible. I've applied `pylint` to much of the code I've worked on but there is the refactoring of `DNATracing` and `Plotting` as well as bits of `Grains`/`GrainStats` which would help those to be undertaken first.
=> Introduce pre-commit

tests/test_utils.py, topostats/run_topostats.py, topostats/utils.py
Closes #337 
Handles taking the relative path of each image found within `base_dir` and creates the directory (minus any filename) under the `output_dir`.
The key is using the `.relative_to` method, but careful attention is required in case the `output_dir` is _not_ within the `base_dir` and is somewhere completely different.
=> Use pathlib methods to resolve directory paths in get_out_path()

topostats/run_topostats.py, topostats/validation.py
Closes #323 
Adds `io.validate_plotting()` function and incorporates it into `run_topostats.py` so that the plotting dictionary/YAML configuration is validated. I also took the opportunity to add a command line argument for users to provide their own plotting configuration YAML file.
Also noticed that whilst I had removed `output_dir` from `Grains()` in #325 as it was no longer used and should have been in `run_topostats.py` that on running through `flake8` courtesy of `pre-commit` it threw up the following error...
```
topostats/run_topostats.py:178:9: F841 local variable 'grain_out_path' is assigned to but never used
```
And so I've added a line to ensure that the `grain_out_path` is actually created (I should have had these checks in place much earlier, hope others are using them and …
=> Validating plotting configuration

setup.cfg, topostats/theme.py
Closes #343
Was seeing `PendingDeprecationWarning`'s, majority were resolved by updating to `seaborn-0.12.1` locally. However `topostats/theme.py` still threw a warning.
This updates the code to use the newer interface to selecting colormaps in Matplotlib.
Also took the opportunity to run `pylint topostats/theme.py` and address any reported issues.
=> 343 | Update colormapping to remove PendingDeprecationWarning; pylint

topostats/io.py
I realised that when working with some files/data, the `pySPM.Bruker().pxs` gave a value of [[0.0, "um"],[0.0, "um"]].
This was because the metadata was lost/not included and thus the value for the px_2_nm scaling was 0, causing issues throughout TopoStats.
Where gwyddion defaults to a pixel size of 1m, I have implemented a quick fix which similarly defaults the pixel size to 1nm if this field is 0.
=> Added contingency for spm px_2_nm

.pre-commit-config.yaml
Closes #354
Updating the `repo:` target for `flake8` in the `.pre-commit-config.yaml`. At the same time I've updated all other `rev:` of the enabled repositories/hooks.
=> 354 | Update flake8 repo for pre-commit; pre-commit autoupdate

.github/workflows/sphinx_docs_to_gh_pages.yaml, .github/workflows/tests.yaml
Closes #363 
Closes #345 
Updating workflows to run against `main` branch rather than `dev` now the branches have been renamed and the default branch switched to `main`.
Also updating the revisions for actions that are used, they were quite dated and resulted in a number of warnings.
Unfortunately we can't yet add Python 3.11.* to the `python-version` matrix for tests (this caused errors during package installation, see [previous PR](https://github.com/AFM-SPM/TopoStats/pull/346#issuecomment-1292192571). These have been fixed  (see [merged PR](https://github.com/h5py/h5py/pull/2165)) but reading the thread a new version release is still pending.
=> 363 | Updating workflows: work with main; update actions

.pre-commit-config.yaml
=> 385 | Excluding *.ipynb files from pre-commit linting.

.pre-commit-config.yaml
Closes #291
Enables a local hook (so that the local virtual environment is used) to run [pylint](https://pylint.pycqa.org/en/latest/) in pre-commit actions. 
* Existing `.pylintrc` in the repository is used.
* `topostats/_version.py` is ignored as this is an external file included by [versioneer](https://github.com/python-versioneer/python-versioneer) and is used for correctly determining package version based on tags when publishing to PyPI.
* Linting is restricted to the `topostats/` and `tests/` directories.
If you are able to test this that would be great (it should only run the linting against files that have changed).
=> Enabling pylint in .pre-commit-config.yaml

setup.cfg, topostats/filters.py
Very minor changes I noticed in `topostats/filters.py` with regards to logging with the `self.filename` rather than `img_name`.  Also disables a few `pylint` errors although they suggest some refactoring _may_ be useful (low priority though).
Also includes a change to `setup.cfg` to pin the Numpy version because a deprecation of methods causes problems with the `igor` library (see [comment](https://github.com/AFM-SPM/TopoStats/pull/409#issuecomment-1359184427)).
To pull this change over use [git cherry-pick](https://www.atlassian.com/git/tutorials/cherry-pick) after this commit has been merged...
```
git checkout main && git pull
git checkout <your-branch>
git cherry-pick 4ca0e43
```
=> img_name from methods > self.filename; disabling flake8/pylint checks

tests/test_validation.py, topostats/validation.py
Closes #423
I understand the problem but do not feel this is an optimal solution given the situation that these absolute thresholds are image specific and the aim to use TopoStats to batch process images.
There are two threads here...
1) The need to have sensible values against which validation is performed as noted for discussion in #302.
2) The challenge of trying to write software and have defaults that cover all scenarios (or say ~80%).
Given the threshold can change on a per-image basis I do not think having user specified `absolute_threshold` for batch processing is sensible. Its highly likely some in a given batch will fail, users then split their batch of images into smaller batches with custom configs and process these. This seems convoluted and against the aim of batch …
=> Relaxes validation of absolute_threshold

tests/conftest.py, tests/test_io.py, tests/test_plottingfuncs.py, tests/test_utils.py, topostats/default_config.yaml, topostats/grains.py, topostats/grainstats.py, topostats/io.py, topostats/plottingfuncs.py, topostats/run_topostats.py, topostats/utils.py
Closes #362 
Closes #391 
Closes #428 
Closes #430 
Closes #433 
Pull request and code changes grew after initially making #429 (see for useful comments/feedback) but in summary...
`LoadScans()` class gets the filename using `Path.stem` method. However `processed_scan()` in `run_topostats.py` also took `Path.stem` so if filenames had two (or more) periods in them the filename ended up truncated and the last two sections after periods were excised (e.g. `mini.circle.spm` > `mini`). This is resolved by using `Path.name` in `processed_scan()` now instead.
There were also some problems with the `utils.get_out_path()` function which have been corrected but aren't easily visible because of having moved the function from `utils.py` to `io.py`.
* Retain a `processed` directory for _each_ level of …
=> Corrects image paths, lints code, adds command line options and more

.pre-commit-config.yaml, .pylintrc, README.md, tests/test_plottingfuncs.py, topostats/filters.py, topostats/plottingfuncs.py, topostats/theme.py
Closes #357
Introduces [pre-commit.ci](https://pre-commit.ci) to the GitHub Actions.
Also applies `black` to the files modified in PR #409
=> Enabling pre-commit.ci on the repo; applying black to plotting files

topostats/validation.py
Closes #459 
This PR adds the commonly used "Height Sensor" channel to `validation.py`.
=> Add Height Sensor channel to validation.py

.github/ISSUE_TEMPLATE/bug_report.md, topostats/run_topostats.py
As discussed in todays meeting (but not noted in a specific issue) it would be useful to report the full version, including a commit hash if we are working on development.
This PR updates the `bug_repor.md` template to request that, including instructions on how to obtain it.
To assist a command line argument `-v/--version` has been added to `run_topostats` which reports the version.
=> Update Bug template to request commit hash; TopoStats arg to show version

docs/usage.md, tests/test_io.py, topostats/io.py, topostats/plotting.py
@derollins was testing the `plotting` refactor and found some errors. This PR corrects those.
The `write_yaml()` function had a hard coding to convert `Path()` objects in a configuration dictionary to `str` for writing to file. That is now done by the `path_to_str()` function (tests included) and in doing so removes the need for the presence of `base_dir: ./` in the `summary_config.yaml`.
Also if a `df` is not passed to the `TopoSum` class when it was being instantiated nothing could be plotted. If no `df` is provided in the `config` (which `run_topostats` adds before plotting) then `TopoSum` now loads the provided `csv` file and the plotting can proceed.
=> Fixing plotting in light of feedback

.github/workflows/tests.yaml, setup.cfg
Closes #345
The `h5py-3.7.0` package had some [issues](https://github.com/h5py/h5py/pull/2165) which were addressed and merged into `h5py-3.8.0` which was released 2023-01-23. This should mean that TopoStats tests run against Python 3.11 and so making an empty commit so I can create a Pull Request and test.
=> Empty commit to trigger workflows with 3.11

.pre-commit-config.yaml, README.md, docs/configuration.md, docs/contributing.md, docs/data_dictionary.md, docs/glossary.md, docs/installation.md, docs/introduction.md, docs/usage.md, docs/workflow.md
Closes #490
One off linting of Markdown files.
Tested `name-tests-test` but opted to remove it as the hook only supports `.*_test.py` whilst [`pytest`](https://docs.pytest.org/en/7.1.x/how-to/usage.html#usage) and the convention we've used supports `test_*.py`.
=> Additional pre-commit checks

topostats/run_topostats.py
Closes #522
Order of actions was incorrect resulting in the default `output` directory being created when `--create-config-file` option was used (this exits after writing the YAML file).
=> Move creation of output directory to after config file generation

notebooks/02-Summary-statistics-and-plots.ipynb, tests/test_plotting.py
Closes #479
Contrary to the title `plotting.py`, which uses Seaborn, produces consistent bin-width when the range of values differs between images. The Jupyter Notebook (`notebooks/02-Summary-statistics-and-plots.ipynb`) uses Pandas for loading data and plotting it (a deliberate choice to reduce the number of packages users would encounter) and it is Pandas which produces the different bin-widths (see [#22222 ENH: groupby.hist bins don't match](https://github.com/pandas-dev/pandas/issues/22222)).
The Notebook has been updated to show how to use `np.linspace()` across the total range of data.
Docstrings of `tests/test_plotting.py` have also been improved.
=> Consistent bin-width in histograms summarising multiple images

topostats/processing.py, topostats/run_topostats.py
Closes #537 
This error was caused by the `summary_stats`/`run` option being `false`, and so the variable `summary_config` was never assigned before being accessed by `completion_message`.
- This PR fixes the issue of the call to `completion_message` crashing due to an unassigned variable `summary_config`, by setting `summary_config` to `None` by default.
- It also adds a message that replaces the directory for the summary stats in the completion message (if the summary stats are not generated).
=> Fix summary_config undefined in completion message

topostats/plotting.py, topostats/utils.py
Closes #514 
Small patch to fix #514 where a grainstats DataFrame was not being returned from `create_empty_dataframe()` due to the `inplace=True` flag of `set_index` meant that the returned value was None, rather than the dataframe which was being acted on.
As a result of fixing that issue, `plotting.py` had an issue where it could not handle a dataframe of only `nan`s, and so I have added a hasty solution to fix that, detecting empty dataframes and simply declaring it and exiting. Please do suggest better alternatives or behaviours if you can think of any.
I also removed some parentheses around a tuple which feels wrong, but Pylint knows best.
Please verify that this fixes #514 on your system too if you have time. Thanks! 😄
=> Sylvia whittle/514 grainstats assignment

tests/test_processing.py, tests/test_utils.py, topostats/grains.py, topostats/processing.py, topostats/run_topostats.py, topostats/utils.py
Fixes a bug where TopoStats would crash just before saving results to csv, on calling `results.reset_index()`. After a lot of digging, it appears that this is caused by a line in `create_empty_dataframe` that sets the index of the empty dataframe to `molecule_number` without then removing the column name `molecule_number`. This then causes a crash when `reset_index()` attempts to turn the index column `molecule_number` into a regular column, since there is already a regular column of the same name.
This issue only happens if grainstats returns an empty dataframe, and so was difficult and rare to find. The solution that I have proposed brings the dataframe that is returned by `create_empty_dataframe()` in line with the dataframes that are returned by grainstats when grains have been found, …
=> Sylvia whittle/pandas reset index error

tests/test_processing.py, topostats/grains.py, topostats/processing.py
Fixes the error we found last week where images that had no grains would crash TopoStats. This was due to sometimes returning an empty `defaultdict` object, and sometimes returning `None` instead.
This solution fixes that issue, and another issue, that had not been noticed yet, where if you were to run an image and request grains to be found in both directions `above` and `below`, then it would detect grains in `below` fine, but if when detecting grains in `above`, it found no grains, then it would error out, and skip steps for both the `above` and `below` directions. 
I fix this by checking explicitly for each direction before calling grainstats. This also gives a more informative output message, so you know which direction found no grains:
```
[Tue, 09 May 2023 13:37:26] [INFO    ] …
```
=> Fix no grains found crash

.github/workflows/ORDA.yaml, README.md
Closes #418
Adds a GitHub Action to publish to ORDA (using the template [here](https://github.com/RSE-Sheffield/release_to_ORDA)).
The `FIGSHARE_TOKEN` has been generated and saved to the repositories settings and as noted in the workflow itself a new TopoStats `FIGSHARE_ARTICLE_ID` for the v2.* series.
=> ORDA GitHub Action

README.md, topostats/processing.py
Closes #541 
Adds simple checks to ensure that the `filters` and `grains` directories are only created when `image_set` is `"all"`.
I can't imagine this having any conflicts, and I tried running TopoStats a few times with various configurations including `image_set: "core"` and `image_set: "all"`, but I could have missed something.
=> Only create filters, grains dirs when image_set is "all"

.github/workflows/pypi.yaml
I realised I'd encountered the issue with the package name not being correctly picked up and built as `UNKNOWN` which results in `Error InvalidDistribution: Metadata is missing required fields: Name` when trying to upload and solved it for another package (see [here](https://github.com/claritychallenge/clarity/issues/266)).
=> Updating package build to work with Debian System

tests/test_io.py, topostats/io.py, topostats/run_topostats.py
Closes #536 
This PR changes the behaviour of generating config files using the command-line flag `--create-config-file`, so that it uses `shutil` to copy the `default_config.yaml` file directly. This is a trade-off on functionality, but it seems that users would prefer the convenience of having the comments in the file.
If it turns out that the users do not end up liking this change, it should be trivial to reverse it as it's a small change that does not affect any other code as far as I can tell.
=> Include comments in config files generated with --create-config-file

pyproject.toml
Adding `pytest-xdist` and `pytest-durations` to the `dev` dependencies, they're useful to have and I found they were missing when I setup a clean environment to check/test #633, reduces a bit of developer friction to have these installed automatically.
I've also disabled `PendingDperecationWarning` from `pytest` reporting and made a note for myself to report this as an issue for the warnings that we now won't see (requires registering at SourceForge which is a blast from the past!)
=> Adds pytest exts to dev dependencies; disables some pytest warnings

tests/conftest.py, tests/test_plottingfuncs.py, topostats/plottingfuncs.py, topostats/processing.py
Closes #657 
This PR fixes the issue where TopoStats would output images scaled in pixels if `Filters` had not been ran.
The issue happened because the code that adds the `pixel_to_nanometre_scaling` factor into the `plotting_dictionary` was inside the `run_filters` function. I have created a function for this code, added a test for it, and moved it out front into `process_scan` as it should always be run.
See here `minicircles.spm` successfully plotted in nanometres without `Filters` being ran.
=> Fix plotting in pixels for topostats files

topostats/grainstats.py
Noticed that no grainstats were being made when cropped_size = -1
Was due to incorrect dictionary keys being called
=> Changed dict crop_size -1 names to match processing

topostats/grain_finding_cats_unet.py, topostats/grains.py, topostats/plotting.py, topostats/plottingfuncs.py, topostats/processing.py, topostats/run_topostats.py, topostats/theme.py, topostats/tracing/dnatracing.py, topostats/tracing/skeletonize.py, topostats/tracing/tracingfuncs.py, topostats/utils.py, topostats/validation.py
This replaces the `box_length` window, and window associated functions with using the whole grain / image / skeleton reducing the window-size dependancy for longer node regions.
It's been made to work the window-based functions with as little changes as possible to make the merge easier to read. 
@llwiggins mind taking a quick look on Monday? If you see anything that could be streamlined / made easier to read let me know :)
=> Maxgamill sheffield/cats window

.github/workflows/tests.yaml, pyproject.toml, topostats/io.py
Closes #682
We had pegged `numpy==1.23.4` because the unmaintained [igor](https://pypi.org/project/igor/) used the now deprecated `np.complex`. By switching to the continuation project [igor2](https://pypi.org/project/igor2/) which still sees active maintenance we are able to remove the fixed numpy version.
I've also taken the liberty to remove `flake8` packages from the list of `dev` optional-dependencies as we no longer have `pre-commit` hooks in place and the task is done by `ruff` and added `ipython` as its a commonly used alternative to plain Python interface (I prefer it as it has additional/commands but always forget to install it in new VirtualEnvs I setup for testing).
My initial thought on why tests were failing with my attempt to upgrade to `igor2` and remove `numpy==1.23.4` …
=> Switch to igor2 for .ibw and unpeg NumPy

tests/tracing/test_dnatracing_single_grain.py
Closes #672 by removing a test that wasn't actually doing anything.
=> Remove redundant test

.github/ISSUE_TEMPLATE/bug_report.md
Closes #120
Removing `Optional` from the bug report template as its really useful to have details of all installed packages when investigating.
=> Explicit request of Python packages in Bug Reports

topostats/filters.py
This PR just fixes an issue I introduced accidentally when implementing `nonlinear_polynomial_removal`, where that flattening step is not run when scar removal is disabled. I initially only incorporated the nonlinear polynomial removal into the pipeline when scar removal is enabled.
This happened because I forgot to add the "initial_nonlinear_polynomial_removal" and "masked_nonlinear_polynomial_removal" to the `else` branch of the checks to see if scar removal is enabled. This resulted in the scar removal result images, "initial_scar_removal" and "secondary_scar_removal" to be set to the flattening step before the nonlinear polynomial removal, ignoring the nonlinear polynomial removal.
I have fixed this by simply switching the images that "initial_scar_removal" and …
=> Fix flattening step not running when scar removal disabled

.github/workflows/add-issue-to-project.yaml
Seems the full version of this action is required and we can't use partial versions.
=> Revert version to full

pyproject.toml, topostats/__init__.py
I came across [snoop](https://github.com/alexmojaki/snoop) which provides a powerful set of debuggin tools and think it would be useful to use it in TopoStats.
This PR adds it as a dependency and imports during package initialisation. By default though it is disabled so that performance in not impacted, this is done by `snoop.install(enabled=False)` in `__init__.py`.
To enable and using during development add the `@snoop` decorator to a function, method or class and in the same file re-enable dynamically by calling `snoop.install(enabled=True)`. See the documentation for more information on usage.
=> Add snoop as a dependency but disable by default

.github/workflows/tests.yaml
As per advice in #721 this PR will mean that there will only ever be [one run per Pull Request/branch at a time](https://learn.scientific-python.org/development/guides/gha-basic/#advanced-usage) cancelling older runs when new ones are triggered e.g. by new pushes to an open Pull Request.
Closes #763
=> Auto-cancel repeated PRs

tests/test_utils.py, tests/tracing/test_dnatracing_multigrain.py, topostats/tracing/dnatracing.py, topostats/utils.py
Further to #752 I've worked through this for my own clarity, apologies for the protracted length and [Rubber Duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging) debugging.
From #752 [comment](https://github.com/AFM-SPM/TopoStats/pull/752#issuecomment-1855640458)
>
> I agree that the coords should not be < 0.
This is the easy bit! Given image...
``` python
import numpy as np
test = np.asarray([[0, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 0],
])
co_ordinates = np.argwhere(test == 1)
index_width = 2
nrows, ncols = test.shape
trace_coordinate = co_ordinates[0]
```
Taking the first co-ordinate, currently what we test is...
```python
trace_coordinate[0] < 0
```
We know that `trace_coordinate[0]` (and in turn `trace_coordinate[1]`) will never be < 0 so …
=> reduced max trace coord idx by 1 so within image bounds

.pre-commit-config.yaml
+ `debug-statements` - Checks for debug statements before commits.
+ `no-commit-to-branch` - Prevents commits being made to specific branches (`main` and `master` by default).
=> Adds some useful pre-commit/pre-commit-hooks

.gitignore, docs/configuration.md, topostats/entry_point.py, topostats/io.py
Closes #761
Introduces the `topostats create-matplotlibrc` sub-command/entry point to write the default style file (`topostats/topostats.mplstyle`) to disk for modification and subsequent usage. The path and filename can be customised when invoking.
This doesn't necessarily mean that all aspects of image plotting are controlled since we set default filenames, titles and DPI and whether an image is in the `core` set via the `topostats/plotting_dictionary.yaml` file.
Documentation has been added that, hopefully, clarifies how to use this in light of this and points users to the relevant Matplotlib documentation for customising parameters in the generated configuration file.
@derollins : I've included you as a reviewer as you requested this feature in #761. I've tested and it seems to work …
=> Adds entry point to create matplotlibrc parameters file

.gitignore, pyproject.toml
Closes #774
+ Adds [NPY201](https://docs.astral.sh/ruff/rules/numpy2-deprecation/) linting to `ruff` which checks for Numpy2 deprecations.
+ Also ignores Notebook checkpoints directory.
Ruff has been run against the code-base and no problems reported. This doesn't mean TopoStats will work with Numpy2 is released as some dependencies may be affected. A useful summary of how to handle potential problems is provided at [Numpy #24300](https://github.com/numpy/numpy/issues/24300) and broadly suggests pinning `numpy<2.0` for releases whilst development proceeds on resolving issues.
=> Check for Numpy2 deprecations

pyproject.toml
The upstream [issue](https://gitlab.com/uweschmitt/pytest-regtest/-/issues/20) has been resolved with the release of pytest-regtest-2.0.2 so unpegging the dependency.
=> Unpeg pytest-regtest

.github/workflows/pypi.yaml
PyPI have introduced the option to publish from trusted environments using [OpenID Connect](https://docs.pypi.org/trusted-publishers/adding-a-publisher/).
Following the [instructions](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) it is recommended to include an `environment` under which the workflow runs.
To this end `pypi-publish` environment has been created for the TopoStats repository and this PR adds the `environment: pypi-publish` configuration to the `jobs.build-release`. At the same time a trusted publisher has been [added](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) to the `topostats` account on PyPI.
=> Add environment to pypi.yaml publishing workflow

pyproject.toml
Author of [pytest-regtest](https://gitlab.com/uweschmitt/pytest-regtest/-/issues/19) has suggested this is no longer needed. I've checked in a clean environment and with `pytest-regtest-2.0.3` and `pytest-7.4.4` this is indeed no longer the case.
Thus we can remove it as a required (optional) dependency.
=> Removes py as a test dependency

tests/conftest.py, tests/test_io.py, topostats/io.py
2 line fix! (No issue made as it would take so much longer)
Code broke on very small scans when e.g. a 1x512px scan came through and thus the scale bar of one side was 'pm' not 'nm' or 'um'. Although these are removed due to the image size limits, they currently the rest of the code from running.
This fix adds no tests because these come from the channel data (a pySPM object) and the values identified here that could be tested are returned from a pySPM function and not a child object thus cannot be overwritten.
We are fine with this not being tested.
=> Added 'pm' and 'mm' for very small and large scans

topostats/processing.py
Closes #802
Arrays and data are now saved in HDF5 files (#790) and so `.npy` arrays are somewhat redundant. This PR leaves the `io.save_array()` function in place should interactive use require saving of arrays but removes its use from `topostats.processing.run_filters()` so that the `.npy` files are no longer saved to disk.
Users wishing to access processed data should load it from the HDF5 formatted `.topostats` files that are saved during processing.
=> Remove saving of gaussian filtered arrays to .npy files

tests/test_entry_point.py, topostats/entry_point.py, topostats/io.py
I noticed that the type of arguments could be set to Path and so have updated our `entry_point` `argparse` to use this.
This also required a small change to convert `Path() > str` when creating output files and tweaks to the tests to ensure targets were of type `Path()`. Whilst updating these I noticed that some of the targets had spaces at the start, this was caused by flags and arguments being combined in the list that are passed (i.e. `"-c default_config.yaml"`) has been corrected so that they are separate items in the list (i.e. `"-c", "default_config.yaml"`) and the spaces at the start of the targets are no longer required.
=> Sets the type of all arguments that are files/paths to Path

tests/test_utils.py, topostats/default_config.yaml, topostats/io.py, topostats/utils.py
Closes #807
Current process is...
1. `topostats/entry_point.create_parser` : get arguments from commandline via the `process_parser` subparser (includes DPI)
2. `topostats/run_topostats.run_topostats()` : loads the dictionary and updates it with any values from `arg`, will update `savefig_dpi` with `--savefig-dpi` value.
3. Validate the updated configuration.
4. Load the default `topostats/plotting_dictionary.yaml` to the main `config["plotting"]["plot_dict"]"`. This adds in all the image specific settings such as title and importantly DPI values for each image.
5. Validate the `config["plotting"]` configuration.
6. Update the plotting configuration with via `utils.update_plotting_config()`. This adds all the options _not_ defined in the `plotting_dictionary` with those from …
=> Fixing DPI settings

pyproject.toml, topostats/tracing/dnatracing.py, topostats/tracing/skeletonize.py
Missed a copy and paste tpyo and have corrected `Raito` > `Ratio`.
Also when trying to make the commit `pylint` (via `pre-commit`) checks informed me there were a number of lines in the added docstrings that were beyond the 120 character limit.
I think this may be because Black and Ruff don't touch docstrings, but most IDEs have support to hard-wrap lines at a given length, although in VSCode this appears to require a [plugin](https://stackoverflow.com/questions/43122175/automatically-hard-wrap-lines-at-column-in-vscode).
=> chore(tracing,skeleton): Line length linting; correcting tpyos

.github/workflows/tests.yaml
Noticed in #830 that there was the following warning...
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4, codecov/codecov-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Checked [codecov/codecov-action](https://github.com/codecov/codecov-action) and the latest release if `4.3.0`.
This Pull Request updates the version used to `codecov/codecov-action@v4`
=> chore: Update codecov version used in test workflow

tests/test_plotting.py, topostats/io.py, topostats/plotting.py, topostats/plottingfuncs.py, topostats/run_topostats.py
Closes #828
Deprecation of [legacy API](https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy) was now throwing errors. These have been addressed and the new `files()` API is used in place.
=> bug: Addresses importlib.resources.open_text() deprecation

.readthedocs.yaml, pyproject.toml
Might close #841
Also noticed the `.readthedocs.yaml` had an a couple of errors in where the version was incorrectly specified in one
location and outdated in another.
=> ci: Peg sphinx-autoapi-3.1.0b0

topostats/io.py
Closes #853 
Adds 1 line reciting the original error message passed to a broad try/except.
For `asd` files, there available channels logging output from `AFMReader` is no longer super-seeded and output. Because the other filetypes don't use `AFMReader` yet, they have duplicate "available channel" outputs.
=> add orig err msg in broad channel try/except

docs/installation.md, pyproject.toml, tests/test_io.py, topostats/io.py
Closes #851 
With renaming `topofileformats` > `AFMReader` and removing the former from PyPI we had to update the dependency.
As detailed in #851 the sum of the arrays changes on switching from `topofileformats` > `AFMReader`. The issue notes some details of investigation.
Also took the opportunity to update the installation instructions to make it clearer and include information on installing from GitHub using `pip`.
=> chore: Update dependency to AFMReader

topostats/tracing/disordered_tracing.py, topostats/tracing/splining.py
This PR splits out the dnatrace smoothing functions into the "splining.py" module to TopoStats which does the sole function of smoothing the disordered traces either as TopoStats normally does (average of splines), or Sylvia's rolling window method.
The fitted traces step has been removed as this could cause issues.
No new diagnostic images are produced - as this only works of the coordinates.
1 new core image is added -> The individual splined coordinates mapped onto the image.
(Currently) 2 new stats are added to grainstats -> total_contour_length and average_end_to_end_distance.
Saves molecule smoothed traces, bbox and contour length and e2e distances to the .topostats file.
=> Seperate out Splining from dnaTracing

topostats/processing.py
Commit `de517ff6` inadvertently disabled the broad `try: ... except:` within `run_grains()`. This is being reinstated and will be addressed when #887 is worked on.
=> fix: reinstate grains try except

tests/test_utils.py, topostats/utils.py
+ `test_create_empty_dataframe()` didn't have `molecule_number` reverted to `grain_number`.
+ `topostats.utils.update_plotting_config()` had a clause which only checked if an image was in the `core_set` and failed if it then didn't have a `mask_cmap` entry.
=> test(utils): Fixing broken tests

pyproject.toml, tests/tracing/test_dnatracing_single_grain.py
Cherry pick cecf60fbabe17b12927284b2b5099e5c4c092c4d which removes the restriction of `pytest<8.0.0` and switches to usine `request.getfixturevalue()` for parameterised tests that use fixtures
This is a prelude to fixing these failing tests.
=> tests: Remove restriction on pytest<8.0.0 (cherry pick)

tests/test_plottingfuncs.py, topostats/default_config.yaml, topostats/plottingfuncs.py
The section which automatically dilated masks had been commented out as part of the refactoring for `better-tracing`. This meant that the related test (`tests/test_plottingfuncs.py::test_mask_dilation()`) failed.
After discussion it was decided to remove this functionality completely. We have left the `topostats.plottingfuncs.dilate_binary_image()` which may be used elsewhere. It isn't currently but there _is_ an argument/option in `default_config.yaml` under `mask_smoothing_params` which indicates the dilation is undertaken during smoothing so perhaps we can simplify the code by calling the `dilate_binary_image()` function we have in place with tests and reduce the amount of code within the smoothing module.
Further the step which turns a mask with numbered layers to binary (`0`/`1`) has …
=> fix(plotting): remove dilation if images are large

.github/workflows/tests.yaml, pyproject.toml
Closes #930
Once Topoly performance regression has been resolved we should unpin this upper bound and ideally support upto Python 3.13.
=> ci: restrict supported python version to <3.12

.github/workflows/tests.yaml
Further to #925 it seems that not all pull requests are triggering the `tests.yaml` workflow.
| PR   | Triggered | Workflow            |
|:-----|:----------|:--------------------|
| #925 | :white_check_mark: | [CI Run](https://github.com/AFM-SPM/TopoStats/actions/runs/11123369831?pr=925) |
| #926 | :white_check_mark: | [CI Run](https://github.com/AFM-SPM/TopoStats/actions/runs/11126129773?pr=926) |
| #932 | :x:       | N/A                 |
Not clear why #932 didn't trigger the `tests.yaml` workflow so this PR makes explicit the `type` of activity on `pull_request` that should trigger the event as well as explicitly stating the types of files that should trigger the tests via the `paths` option (as changes to e.g. `*.md` (Markdown) files are never going to affect the outcome of tests.
=> ci: Explicit types of pull requests and paths to run CI tests

pyproject.toml, topostats/tracing/nodestats.py
Resolves #919 
This is a combination of 6 commits which were squashed via [interactive rebasing](https://www.sitepoint.com/git-interactive-rebase-guide/)...
- style(tracing/nodestats): PR02 numpydoc-validation
- style(tracing/nodestats): RT01 numpydoc-validation
- style(tracing/nodestats): GL01 nupydoc-validation
- style(tracing/nodestats): GL02/GL03 numpydoc-validation
- style(tracing/nodestats): PR03 numpydoc-validation
- style(tracing/nodestats): PR01/PR07 numpydoc-validation
=> style(tracing/nodestats): Fix all numpydoc-validation errors

.github/workflows/tests.yaml
Resolves #896
Adds [debugging with tmate](https://github.com/marketplace/actions/debugging-with-tmate) action to `tests.yaml` which
allows SSHing into GitHub Runners _if_ tests have failed.
=> ci: Adds tmate to tests.yaml workflow

pyproject.toml, topostats/theme.py
Fixing missing return docstring and the name in another docstring.
=> style(theme): RT01 Numpydoc Validation

topostats/tracing/nodestats.py
closes #912
Addresses the Nodestats autodoc documentation issues via code blocks.
Added code blocks so documentation rendering doesn't cause errors and also looks better:
=> Fixes the dictionary keys docs formation

docs/usage.md, tests/test_io.py, topostats/io.py, topostats/processing.py, topostats/run_topostats.py
closes #969
TLDR:
PR adds the following:
- Rejigging tracing stats outputs so base grainstats / molstats / None is returned.
- Enables folder stats to be output properly.
- drops empty stats columns causing concat warning.
Think I got it. The cause according to the docs is that pandas doesn't like concatenating objects with whole columns (or rows) as NaN's or None's (we had a mix which is why it was hard to find).
Not only that, but for some reason the "warning" also halts processing.
The initial fix I tried was to stop the warning using the below code which seemed to work, so maybe a 🔥hotfix🔥 idea for something in the future:
```
import warnings
...
warnings.filterwarnings("ignore")
```
Then I thought... WWND (what would @ns-rse do) 👼, and so I solved the root issue and stopped the …
=> Fixes `pd.concat` error halting processing

tests/test_utils.py, topostats/processing.py, topostats/utils.py
- Parameterises `test_utils.py::test_create_empty_dataframe()` so that all three possible empty dataframes are now tested.
- Renames `create_empty_dataframe()` parameter `index` > `index_col` to avoid confusion with Python and Pandas `index` methods.
- Explicitly calls `create_empty_dataframe()` with the `column_set` and `index_col` in each instance rather than relying on defaults when an empty `grainstats_df` is required.
- Further at the end of `process_scan()` empty dataframes of all types were incorrectly generated as no types were specified for any, these now generate the correct type for each required data frame.
=> tests(utils): parameterise test_create_empty_dataframe()

docs/usage.md, tests/test_utils.py, topostats/processing.py, topostats/utils.py
Apologies, the previous PR was a tad early, I thought the "merge when ready" would wait for until tests finished...
This should provide a hotfix to the errors and similar like them:
```
disordered_trace_results[str(img)] = disordered_trace_result.dropna(axis=1, how="all")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dropna'
```
This occurred because the disabled modules would return `None` instead of an empty dataframe and we expected to have the dataframe function `DataFrame.dropna()` which obvs didn't exist.
This fix should ensure that dataframes are returned by disabled modules.
It also adds another exception I found when forcing the disordered traces step to fail causing KeyErrors in NodeStats and Ordered Tracing as they couldn't find the image …
=> Fixes None tracing outputs attempted to be concatenated

tests/tracing/test_disordered_tracing.py, topostats/tracing/disordered_tracing.py
Making a start on the backlog/deficit of unit-tests highlighted in #966.
=> tests(disordered_tracing): Bulks out missing unittests

README.md, docs/configuration.md, docs/usage.md
Amends the docs in `readme.md`, `docs/configuration.md`, and `docs/usage.md` in light of the entry-point changes.
Mainly just adjusts to use: `topostats -c <config>.yaml process
=> update readme.md with new swiss army knife processing order

.github/pull_request_template.md
As [suggested](https://github.com/AFM-SPM/TopoStats/pull/996#issuecomment-2476147390) by @SylviaWhittle we could all do with an _aide memoire_ when making Pull Requests that we have covered everything we should.
This Pull Request therefore introduces just such a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to aid contributors in making sure we have covered everything.
---
=> ci: Adds a Pull Request template

.pre-commit-config.yaml
Closes #1006 
As per [PC180](https://learn.scientific-python.org/development/guides/style#PC180) uses [rbubley/mirrors-prettier](https://github.com/rbubley/mirrors-prettier/) over [pre-commit/mirrors-prettier](https://github.com/pre-commit/mirrors-prettier/).
Please provide a descriptive summary of the changes your Pull Request introduces.
The [Software Development](https://afm-spm.github.io/TopoStats/main/contributing.html#software-development) section of
the Contributing Guidelines may be useful if you are unfamiliar with linting, pre-commit, docstrings and testing.
**NB** - This header should be replaced with the description but please complete the below checklist or a short
description of why a particular item is not relevant.
---
Before submitting a Pull Request please check the …
=> style: Changes prettier mirror used by pre-commit

.github/dependabot.yml, .github/pull_request_template.md
Closes #733 
As per [GH200](https://learn.scientific-python.org/development/guides/gha-basic/#GH200) enables dependabot to check for
updates to GitHub Actions and updates automatically with Pull Requests.
Also tweaks the `.github/pull_request_template.md` to be more explicit about updating documentation.
**NB** This is a Stacked Pull Request and Should be merged after #1011 (as it was branched from
`ns-rse/1006-prettier-update`).
---
**N/A**
=> dependabot for GitHub Actions

pyproject.toml
Closes #1007
As per [RF002](https://learn.scientific-python.org/development/guides/style#RF002): Target version must be set
We had both Ruff's `target-version` and `project.requires-python`. We only need the latter.
**NB** This is a stacked pull request and should be merged after #1012
---
**N/A**
=> config: Removes target-version from ruff configuration

.pre-commit-config.yaml, topostats/run_modules.py
Closes #1005
As per [PC170](https://learn.scientific-python.org/development/guides/style#PC170): Uses PyGrep hooks (only needed if
rST present) adds [pygrep-hooks](https://github.com/pre-commit/pygrep-hooks) to `.pre-commit-config.yaml`.
Opted to enable more than just the `rst-` hooks.
**NB** This is a stacked commit and should be merged after #1013 from which it was branched.
---
**N/A**
=> ci: Adds pygrep-hooks and fixes errors

.gitignore
Uses [gitignore.io](https://www.toptal.com/developers/gitignore) template for Python to exclude intermediary files that
are by-products of working with Python packages.
=> chore: Improves .gitignore to ignore more Python files

topostats/tracing/disordered_tracing.py
- `px2nm` > `pixel_to_nm_scaling` so this keyword is consistent across all functions/methods.
- Removed an unnecessary comment line `# Code will go here`
- Already import `ndimage` from `scipy` so prefixed `distance_transform_edit()` rather than importing it in isolation.
I _haven't_ updated `docs/data_dictionary.md` with the new `grain_width_mean` field that is written to the output files
and will include that in #1001.
---
=> style: Tidying calculate_dna_width()

.gitignore, topostats/run_modules.py, topostats/tracing/ordered_tracing.py
Closes #1039
Pre-commit hooks do fail, but this is expected as there is Work In Progress on the `run_modules.py`
---
=> Remove index column from results plus some other tidying

pyproject.toml, tests/conftest.py, tests/test_io.py, topostats/io.py
Closes #1036
With the delegation of much I/O (Input/Output) functionality to @SylviaWhittle `AFMReader` (see #1031) we have removed most of the methods to the `io.LoadScan()` class. One that slipped through was `_spm_pixel_to_nm_scaling()` and this commit removes it along with its associated test.
Further the delegation of reading AFM files using `AFMReader` means `TopoStats` no longer has explicit dependencies on the `igor2`, `pySPM` or `tifffile` packages and so these have been removed from the `dependencies` section of `pyproject.toml`. These are dependencies of `AFMReader` and will still be installed in virtual environments.
Moved `pytest-testmon` from `tests` to `dev` under optional dependencies as its not used when running the test suite, only when making commits locally.
---
Before …
=> chore: Remove unused method, test and package dependencies

notebooks/OUTDATED-02-Summary-statistics-and-plots.ipynb, notebooks/OUTDATED-03-Plotting-scans.ipynb
One (E712) is a false positive as its used to subset a Pandas DataFrame.
The other two I've no current alternative plan as they involve creating buttons for users to upload files. Not sure
whether these will persist past the notebook refactor (#943) so have disabled the checks for the time being.
---
=> style(notebooks): Ignore Flake8 complaints on Notebooks

pyproject.toml, topostats/tracing/disordered_tracing.py
Closes #986
With the release of `skan-0.12.2` we can remove the code which converts `-` in the variable names of Pandas DataFrames to instead use `_` which allows the use of "dot-notation" when referring to the variables of data frames.
We therefore unpin the `skan` version in `pyproject.toml`, explicitly state the `separator="_"` argument to `skan.summarize()` and adapt the hard-coded variable names appropriately. As noted in the [release notes](https://github.com/jni/skan/releases/tag/v0.12.2) the default will be `_` from `v0.13.0` and the flag allows backwards compatibility but since we have gone with the use of `_` in variable names it will do no harm leaving these in place (although they could be removed when `skan-v0.13.0` is released).
In addressing #986 I tested in a fresh virtual …
=> refactor(disordered_tracing): Work with skan-0.12.2

.github/ISSUE_TEMPLATE/bug_report.yaml
Now that we have changed the verbosity we need to include instructions on how to get detailed log-files included in bug reports.
=> chore: Clarify request for log output in bug reports

topostats/entry_point.py
Closes #1057
In reviewing #1056 I wanted to look at the individual grain curvature plots that were generated and realised that there
was no command-line option to modify the configuration value loaded from the YAML (`topostats/default_config.yaml` or
user specified with `--config-file/-c`).
This means that currently if people want the `all` image set then they have to use `topostats create-config` to create a
configuration file, modify the value of `image_set` and run the analysis with `topostats -c new_config.yaml`.
It was very quick and easy to add this option so I could check the output and as its been done I felt it should be
incorporated into TopoStats.
-------
=> feature: Adds --image-set as option to topostats

tests/test_io.py, tests/test_processing.py, topostats/io.py
Closes #1067
Modifies `LoadScan.load_topostats()` to take an argument `extract: str = "all"` so that by default the cleaned
image (post filter) that is stored at `image`, `px_to_nm_scaling` and `data` that are stored in `.topostats` HDF5 are
returned.
To assist with #517 though it is also possible to specify other data to extract such as `raw` to get the original
image array and `pixel_to_nm_scaling` should the user want to re-run the `Filter` stage and `filter` should the user
wish to re-run the grain detection on the cleaned (post-Filter) array
The user options are mapped to the keys used in the HDF5 structure by means of a dictionary (which is local to the
`.load_topostats()` function) and will be extended as required in subsequent work.
Tests are expanded.
-------
Please provide a …
=> feature: expand objects returned by LoadScan.load_topostats()

topostats/grains.py
Resolves #1066 
This PR resolves the bug found by @tcatley in issue #1066 by combining grain crops rather than overwriting them to avoid issues when multiple bounding boxes overlap one another. 
The image below shows how grain crops are now correctly combined to assemble full image masks.
=> Combine grain crops rather than overwriting them

docs/contributing/adding_modules.md
Also adds a link to the `contributing.md` page so that the `adding_modules.md` page is findable and can be read on the
website!
This will need tweaking when we switch to mkdocs (see #1079)
=> docs|style: line wrapping in adding_modules.md

topostats/unet_masking.py
Really tiny change but Image.NEAREST is now deprecated and needs to be replaced with Image.Resampling.NEAREST to run without error. This is already corrected in the upcoming grains refactor but thought it was worth correcting in main in the meantime!
---
If adding options to `topostats/default_config.yaml` please ensure.
=> Replace deprecated Image.NEAREST with Image.Resampling.NEAREST

pyproject.toml, tests/test_filters.py, tests/test_io.py, tests/test_run_modules.py, topostats/io.py
Closes #1086
Updates the `LoadScans.load_topostats()` and `LoadScans.get_data()` to work with the new version of AFMReader.
~~This means the CI tests _will_ fail because we haven't released AFMReader yet (and I'm wary of doing so until we are ready to make another TopoStats release).~~
EDIT : Updated `pyproject.toml` to install AFMReader from GitHub so tests should pass on CI :crossed_fingers: 
But...tests all pass for me locally(!) with AFMReader installed from `HEAD` of `main` branch.
If you want to check locally you'll need a fresh Python3.11 environment (because `topoly`!) and to install AFMReader from your local git clone (you can install from git using `pip` but I can't remember the command and am not going to look it up now!).
-------
Before submitting a Pull Request please check …
=> fix: Updates io to work with AFMReader only returning data

tests/test_grains.py, tests/test_processing.py
- Spotted a few `print()` statements from debugging.
- Explicitly test the number of grains below that are returned.
- switching to a dictionary in the parameterisaion of `test_merge_classes()` instead of multiple individual
options with comments/labels. The dictionaries are expressive about what the values are since the keys are the
configuration options themselves. This in turn means we can just use `**vet_grains_conf` to unpack the dictionary of
options when calling the `vet_grains()` function.
=> style: using dictionaries for parameters and **kwargs

docs/contributing/adding_modules.md, tests/test_processing.py, tests/test_run_modules.py, topostats/entry_point.py, topostats/io.py, topostats/processing.py, topostats/run_modules.py
Closes #743
Adds an entry point for running GrainStats `process grainstats --help`.
You can test it with...
```
❱ topostats -b tests/resources/test_image -f .topostats grainstats
❱ tree output
[4.0K Feb 24 14:53]  output
├── [2.7K Feb 24 14:53]  output/config.yaml
├── [2.7K Feb 24 14:53]  output/height_profiles.json
├── [1.7K Feb 24 14:53]  output/image_stats.csv
└── [4.0K Feb 24 14:53]  output/processed
└── [109K Feb 24 14:53]  output/processed/minicircle_small.topostats
2 directories, 4 files
```
Unlike with #1076 only the required directory structure is created.
-------
=> feature(grainstats): Adds entry point for grainstats

tests/test_run_modules.py, topostats/processing.py
The refactoring to use classes for objects rather than dictionaries breaks the `topostats grainstats` entry point that
was introduced with #1094.
Previously the dictionary item `image=topostats_object["image"]` was passed into `processing.run_grainstats()` when called from
`processing.process_grainstats()`. The refactoring requires that `image_grain_crop=image_grain_crop`, an object of the new type
`ImageGrainCrops`, is now passed to `grainstats`.
This isn't currently possible though because `AFMReader` loads `.topostats` objects and returns a dictionary and whilst
the refactoring does save the new `image_grain_crop` (/`ImageGrainCrops`) the loading does _not_ currently re-create
these structures.
For now I have disabled the test of the entry point. Once this refactoring has been merged …
=> tests: disable test_run_modules::test_grainstats

tests/test_grains.py, tests/test_io.py, topostats/grains.py, topostats/io.py
Adds a method to convert a `grains.GrainCrop` object to a dictionary (`grains.GrainCrop.grain_crop_to_dict()`) which is
indexed by the attribute names with the attributes as the values. Includes a simple test using the `dummy_graincrop`
fixture.
As this will be needed to convert the nested dictionaries of `ImageGrainCrops` (which hold `GrainCrop` objects within
`GrainCropsDirection`) objects we include a check to see if the `item` (value) of a dictionary is of type `GrainCrop`
and if so recursively call `dict_to_hdf5` on the result of `item.grain_crop_to_dict()`. Again a simple test to ensure
this functions as expected is included.
=> feature(grains|io): Method to convert GrainCrop to dictionary

pyproject.toml, tests/conftest.py, tests/test_grains.py, tests/test_io.py, topostats/grains.py, topostats/io.py
**NB** This is a stacked pull request and should be merged _after_ #1104
Adds a method, based on the `__dict__` "magic dunder" method to convert the `GrainCropsDirection` to a dictionary. Tests
are included not just for the method itself but because this is required in `io.dict_to_hdf5` there are also tests that
it works with that (these are contingent on changes introduced in #1104 because `GrainCrop` are nested within the
`GrainCropsDirection` object).
=> feature(grains|io): GrainCropsDirection to dictionary

pyproject.toml, tests/test_io.py
Closes #1110
In light of the changes to AFMReader which modified the scaling the sum of the arrays of the `.jpk` test files needed
updating here too.
=> tests(jpk): Updates sum of images loaded from JPK

tests/test_io.py
Thanks to @SylviaWhittle :eagle: :eye: in spotting an error in a fixture I added to `tests/conftest.py` I took a closer look at where it was used and spotted some problems with a previous PR of mine was a little hasty/not as thorough as it should have been and most of the `assert` statements were testing equivalence at all.
This corrects that problem.
=> tests(io): Fix test_dict_to_hdf5_graincrop()

tests/test_processing.py
Switches to using dictionaries in parametrisation and within the `test_image_set()` test. Easier to follow the mapping of what should and shouldn't be present.
---
=> refactor(test_processing): list -> dictionaries

tests/test_processing.py, topostats/plotting_dictionary.yaml
The `test_save_cropped_grains()` is parameterised but each set of parameters was missing `pytest.param(... id="")` so I've added these.
Also includes an additional line in the table at the top of `topostats/plotting_dictionary.yaml` which indicates what the newly introduced `module` key/value pair represents.
---
=> style(test_processing): Adds pytest.param( id="")

topostats/io.py, topostats/validation.py
>Please provide a descriptive summary of the changes your Pull Request introduces.
Added load_stp and load_top funtions to process .top and .stp file extension. These formats are used in Nanotec AFMs. 
I have attached and example of these images and config files below:
[test_images.zip](https://github.com/user-attachments/files/19778259/test_images.zip)
---
If adding options to `topostats/default_config.yaml` please ensure.
to ensure entries are valid.
-------
1. Once Sylvias AFMReader branch is merged we could run the tests. `pytest .\tests\`
2. Possibly add a new test for these functions 
3. Turn off draft PR
=> Add code for loading .stp and .top files

tests/conftest.py, tests/test_io.py, tests/test_topostats.py, topostats/__init__.py, topostats/io.py, topostats/processing.py
As we look to move towards restructuring the `.topostats` HDF5 file I've taken the logical extension to the introduction of `ImageGrainCrops` dataclass and the nested dataclass/class by introducing a `TopoStats` dataclass which defines the top-level attributes and structure that we wish to have in `.topostats` files.
One of the disconnects at the moment is that when we run the whole processing pipeline we load whatever image using AFMReader which returns `image` and `pixel_to_nm_scale`. This is ok if we're running the whole pipeline but when it comes to later stages and attempting to load `.topostats` files which can be passed into `Grains`/`GrainStats`/`DisorderedTracing`/etc. then we will be loading a `.topostats` file which is stored as HDF5, initially loaded as a dictionary but we …
=> feature: Introduce TopoStats class and saving to HDF5 .topostats

topostats/__init__.py
If `img_path` is `None` then `TypeError` was raised by `pathlib`. If that is the case it now defaults to `Path.cwd()`.
=> refactor(TopoStats): handle img_path = None

.github/workflows/tests.yaml, pyproject.toml
Closes #1153
Runs tests in parallel and sets the number of jobs to be `auto` which is calculated as the number of _physical_ cores the CPU has.
Other options include using `logical` which, as the name suggests, is the number of logical CPU cores.
For example the `i9=9980HK` in my laptop has 8 physical cores but each one provides two logical CPU cores, i.e. 16 in total.
Since I don't want to tie up my, or anyone elses, system running the test suite I've opted to set the default to the lower of the two (via `auto`).
~~This should help speed up some of the tests run in CI too where the number of cores is unknown.~~
The `pyproject.toml` change _won't_ speed up CI tests since they are configured in `~/.github/workflows/test.yaml` where we invoke `pytest --cov=topostats --mpl -x` and it uses …
=> tests: run tests in parallel via pyproject.toml

.github/workflows/pypi.yaml
Because of the versioning being done automatically via `setuptools_scm` these will always get rejected as the version doesn't conform to the [version specifiers](https://packaging.python.org/en/latest/specifications/version-specifiers/)
=> ci(pypi): Disable job that publishes to TestPyPI

topostats/io.py
Missed this in reviewing the code. We have already extracted the version from `TOPOSTATS_DETAILS` to `TOPOSTATS_VERSION` so may as well import it and do away with having to index the version from `TOPOSTATS_DETAILS`.
TopoStats Pull Requests
=> style: import TOPOSTATS_VERSION rather than TOPOSTATS_DETAILS
