AFM-SPM/TopoStats

- COPYING
- COPYING.LESSER
- README.md
I'd like some RSE team feedback which I'll solicit via slack before putting this to @alicepyne .
> Add license

- README.md
- contributing.md
I've written this as a template for a few different projects - it can be tailored as needed.
> Add contributing instructions

- dnatracing.py
I edited the vague/totally useless comments in getFittedTraces() - would be good to know if the new comments are clear enough for others to understand. Can improve/clarify comments further if necessary.
> 13 fix unclear comments in dnatracing

- pygwytracing.py
Added a line to change the relative file path to a full file path independent of the users OS.
> Relative-to-Full File Path

- .github/workflows/smoke-test.yaml
i.e. we switch it on and see if starts emitting smoke. By which I mean: install and run the software in a standard basic way and see if there's an error.
> Add smoke test

- docs/conf.py
- docs/index.rst
- docs/topostats.dnatracing.rst
- docs/topostats.pygwytracing.rst
- docs/topostats.tracingfuncs.rst
- topostats/dnatracing.py
Draft built version of docs https://topostats.readthedocs.io/en/rtd/
> Finish config readthedocs

- README.md
- contributing.md
Changes to readme and contributing to make them look nicer and be more easy to read and that. Also info on planned software architecture (which can totally change as we go along, just want some kind of plan). More detail on how to use the architecture to follow in #72 .
> Contributing

- .github/workflows/smoke-test.yaml
- .github/workflows/tests.yaml
- docs/topostats.filters.rst
- tests/test_filters.py
- tests/test_regression.py
- topostats/filters.py
Creates a means of adding and testing 2D image filters. May need to be discussed a bit before merging in case what I've proposed doesn't work for other people. Feedback welcome here.
> Filter framework

- .github/workflows/container.yaml
> 124 | Disabling docker container and subsequent smoke tests whilst development continues

- .gitignore
- .readthedocs.yaml
- docs/conf.py
- docs/index.rst
- docs/topostats.find_grains.rst
- docs/topostats.io.rst
- docs/topostats.plottingfuncs.rst
- docs/topostats.pygwytracing.rst
- docs/topostats.topotracing.rst
- docs/topostats.utils.rst
- setup.cfg
Resolves #126 
To test:
```
pip install -e ".[docs]"
cd docs
make html
```
Have a look at `_build/index.html` in a browser.
Readthedocs won't update until we merge so can't be 100% sure this will fix and another iteration may be needed.
> Docs update

- README.md
- docs/installation.md
> 174 | Improving installation instructions

- tests/conftest.py
- tests/test_grains.py
- tests/test_grainstats.py
- topostats/filters.py
- topostats/grains.py
- topostats/grainstats.py
- topostats/logs/logs.py
- topostats/run_topostats.py
- topostats/thresholds.py
- topostats/utils.py
This is still a work in progress and subject to change when thresholding/filtering is revised, so I will update things when that is available. However it hopefully fails gracefully when no grains are found.
I think long-term we should consider bulking out the test-suite with more than just `minicircle.spm`, a `silicon.spm`, `water.spm` and more will be really useful.
Also tidied up via some linting and applied Black formatting in a few places that hadn't had that treatment.
> 186 | Fail gracefully when no grains found

- Plotting.py
Updating the dictionary and unit conversion to accommodate the output of new TopoStats. Fixing the lack of brackets in some printing statements.
> Dictionary update

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
I'm planning to merge this as admin as it was approved for master https://github.com/AFM-SPM/TopoStats/pull/93
> Issue templates (done in `master` needed in `dev` also

- .github/workflows/sphinx_docs_to_gh_pages.yaml
Resolves #236 
Adds a workflow to build the website and host it on GitHub Pages.
> 236 | Adding workflow to build docs on GitHub Pages

- docs/index.rst
- docs/related_software.md
> 247 | Adds a related software page to the website

- tests/conftest.py
- tests/resources/process_scan_config.yaml
- tests/resources/sample_config.yaml
- tests/test_filters.py
- topostats/default_config.yaml
- topostats/filters.py
- topostats/run_topostats.py
- topostats/validation.py
> 310 | Removes amplify_level from codebase

- topostats/default_config.yaml
Reordered the 'grains' section of the config file so that it's clearer to users
closes #319
> Reordered the 'grains' section of the config file

- tests/conftest.py
- topostats/default_config.yaml
> Reverts default threshold_method to std_dev; updates tests

- .pre-commit-config.yaml
Adds a commented out section to run [`pylint`]() against the code base.
The reason its commented out for now is that `pylint` reports a _lot_ of errors with the current code base. The current errors are reported below, most are with `DNATracing` (which I _will_ get round to refactoring) and some with `Plotting` which is also on my `ToDo` refactoring list (may address first as @Jean-Du code is easier to work with). Mostly `Filters` / `Grains` / `GrainStats` don't have too many issues. Once the two main offending modules are refactored I would be keen to uncomment this and have it used more widely, including a GitHub Action.
If you want to run this locally then after this PR has been merged to `dev` you can ...
1. `pip install .[dev]`
2. Uncomment the last section of …
> Adds (disabled) hook for running pylint using system pylint 

- CITATION.cff
- README.md
- setup.cfg
Closes #380 
Adding a `CITATION.cff`, wasn't sure/couldn't find ORCID ID's for everyone if you have one please let me know and I'll add it.
Tweaked and augmented the badges on the project and tidied up the `README.md` as there were a few inconsistencies.
> 380 | Adds Citation File Format file; Tweaks README and metadata

- .pre-commit-config.yaml
- .pylintrc
- setup.cfg
- tests/test_validation.py
- topostats/run_topostats.py
- topostats/validation.py
> 384 | Refactors validation and introduces test for validate_config()

- .github/workflows/add-issue-to-project.yaml
Not sure this will work as its a Personal Access Token generated from my account rather than the AFM-SPM organisation.
> Attempt to use Personal Access Token

- docs/configuration.md
- docs/faq.md
- docs/glossary.md
- docs/index.rst
Closes #201
Adding documentation in the absence of being able to resolve network drive errors.
> Adding FAQ and Glossary; tidying configuration

- .github/ISSUE_TEMPLATE/bug_report.md
Closes #495
Feedback welcome, has anything been missed, could anything be clearer?
> Updating bug report template

- .github/ISSUE_TEMPLATE/bug_report.md
> Clarifying running analyses sequentially

- .pre-commit-config.yaml
- CODE_OF_CONDUCT.md
> Fixing markdownlint-cli2 errors

- docs/contributing.md
- docs/notebooks.md
> Quotes around installation of extra requirements

- CITATION.cff
> Updating CITATION.cff

- topostats/io.py
This means the reported available channels in the logger error message are actually what you need to put into the config file.
> User facing channel names swapped for bts channel names

- pyproject.toml
- tests/test_filters.py
Closes #608
Currently includes a test that will fail which will be removed in due course.
> Add pytest-github-actions-annotate-failures

- topostats/plotting.py
- topostats/processing.py
- topostats/tracing/dnatracing.py
- topostats/tracing/skeletonize.py
Adds confidence and average confidence values into the nodestats and grainstats dataframes
> Merging confidence value work into cats branch

- tests/test_entry_point.py
- topostats/entry_point.py
Adds very basic subparsers for each of the modular steps...
+ `load`
+ `filter`
+ `grains`
+ `grainstats`
+ `dnatracing`
+ `tracingstats`
...and tests that each returns the appropriate help. Will serve as a basis for subsequent development of each.
> Adds subparsers for further modularisation

- pyproject.toml
- tests/test_utils.py
- topostats/utils.py
Highlighted by https://scientific-python.org [repo-review tool](https://learn.scientific-python.org/development/guides/repo-review/) I had missed this out.
> Minor tweak to pyproject.toml config

- pyproject.toml
> pytest<8.0.0

- topostats/default_config.yaml
Very small PR correcting erroneous replacement of lower with below.
> Typo correction to default_config.yaml

- topostats/tracing/dnatracing.py
- topostats/tracing/pruning.py
- topostats/tracing/skeletonize.py
Updates docstrings with missing values and explanations
> Update dnatracing docstrings

- .github/workflows/sphinx_docs_to_gh_pages.yaml
> ci(gh-pages): Build docs on PRs to main branch only

- topostats/__init__.py
> chore(init): Update registration of colormaps

- pyproject.toml
> test: Adds pytest-icdiff to dev dependencies

- tests/test_processing.py
- topostats/processing.py
Closes #899
Also updates `test_process_stages()` although this includes disabling a one set of parameters for the time being until I work out what is now happening.
**NB** This should be merged **BEFORE** #900 so that that Pull Request/branch gets updated with these changes and everything is then merged into `maxgamill-sheffield/800-better-tracing`.
> tests(processing): Improves logic and tests for check_run_steps()

- .github/workflows/tests.yaml
> ci: Run tests workflow on all pull_request

- tests/tracing/test_disordered_tracing.py
- tests/tracing/test_nodestats.py
- tests/tracing/test_skeletonize.py
- topostats/tracing/disordered_tracing.py
- topostats/tracing/nodestats.py
I've also...
- Added place holders for missing disordered_tracing tests.
- Removed hard coding of variable renaming which replaced `-` with `_` so its generic.
> fix(disordered_tracing): force branch_type to int64

- README.md
Was notified of [howfairis](https://github.com/fair-software/howfairis) repository checker by @tdjames1 so ran it against the repository and am adding the badge provided.
> chore: Adds fair-software.eu badge to README.md

- pyproject.toml
- topostats/__init__.py
- topostats/processing.py
Prints "TopoStast" using the [art]() package and the "twisted" font which I felt was appropriate for DNA!
> feature: Print 'art' above completion message

- .github/dependabot.yml
As per [GH212](https://learn.scientific-python.org/development/guides/gha-basic/#GH212) groups github-actions updates via dependabot to reduce pull requests.
---
If adding options to `topostats/default_config.yaml` please ensure.
**N/A**
> ci: group dependabot github-actions updates

- CITATION.cff
Closes #1021
If anyone has missing information (mostly email and one ORCID) for those being added please leave as a suggestion in the Pull Request and we can add it in.
---
**NA** No code changes in this PR
> chore: Adds earlier contributors to CITATION.cff

- README.md
Closes #1026
---
**NA** Code does not include any changes to code
> docs: Adds Under/Over preprint link to Publications of README.md

- docs/contributing/adding_modules.md
Closes #989
As I go through writing additional entry points for #517 I thought it worth documenting how to incorporate functionality
into the workflow in terms of adding it to the end-to-end pipeline and how to create an additional entry point so that
the specific functionality can be run on its own.
This is based on having done `filters` (#741) over a few weeks and as I go forward with subsequent (e.g. #742) which I've
started I may well tweak/revise these notes in case I've missed anything or made mistakes.
> docs: how to add functions and modules

- docs/workflow.md
Closes #1074
Uses [GitDiagram](https://gitdiagram.com) to generate an overview of workflow for TopoStats. Its not quite as detailed
at the moment but I feel it will be is informative and useful to those coming to the project anew.
> docs: Clearer workflow overview

- topostats/processing.py
Closes #1076
-------
Please provide a descriptive summary of the changes your Pull Request introduces.
The [Software Development](https://afm-spm.github.io/TopoStats/main/contributing.html#software-development) section of
the Contributing Guidelines may be useful if you are unfamiliar with linting, pre-commit, docstrings and testing.
**NB** - This header should be replaced with the description but please complete the below checklist or a short
description of why a particular item is not relevant.
---
> fix(processing): create grains/dnatracing directories if needed
